<div id="bios">
			
            <h3>Jan Stefanski</h3><br />
            <p><img src= "<?php echo URL ?>public/images/about/jan.jpg" alt = "jan" class= "biophoto" align="left" width="140px" />Jan, co-founder of Janus Consulting, has over 35 years of experience in the planning, design and implementation of a variety of business solutions. His primary focus is to assist clients in achieving their stated business goals and planning for the future.  He effectively and efficiently blends the business, social, economic and technical aspects of a situation to achieve the desired results, especially cross-functional initiatives.  He has worked in a number of industries, both domestic and international.  Jan makes &#39;fuzzy things clear&#39;, assisting clients from &#39;idea crystallization to operations&#39;.</p>
            <p>Jan understands the need for measureable business results.  His strength lies in his ability to explore, understand and integrate the realities of the client&#39;s business and organizational context.  To provide the best sustainable solution for a given situation, Jan blends his previous business experiences, learnings from a variety team settings, academic knowledge, and an in-depth understanding of a wide range of tools and techniques. His approach in team development and effectiveness is pragmatic, systemic, facilitative and collaborative with clients and other consultants.  </p>
            <p>Jan holds a B.S. degree in Physics from St. Joseph&#39;s University and an MBA in Finance from Drexel University.   Jan is a certified Myers-Briggs Type Indicator (MBTI) instructor and has been trained in mediation techniques by the Academy for Workplace Dispute Resolution. Jan has been a guest lecturer at the University of Pennsylvania, Villanova University, Saint Joseph&#39;s University and Drexel University.  He is a member of the advisory board for St. Joseph&#39;s University&#39;s College of Professional and Liberal Studies. </p>
            <p>Jan&#39;s services include: team development, coaching, consulting, facilitation and instructor-led training. </p>
            
            <hr />
          
</div>